// Generated by CoffeeScript 1.6.1
(function() {
  var http, onRequest;

  http = require('http');

  onRequest = function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.write('Another damn test');
    console.log("Request received, makin a change");
    return response.end();
  };

  console.log("Here goes another thing!");

  http.createServer(onRequest).listen(8000);

}).call(this);
