// Generated by CoffeeScript 1.6.1
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    res.write('God damnit Donny');
    return res.end();
  });

  console.log("Starting Server!");

  server.listen(8000);

}).call(this);
